name: GitHub Actions to Dockerhub
run-name: ${{ github.actor }} test GitHub Actions to upload docker image 🚀
on: [push]
jobs:
  Build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: build and tag image
      run: |
        docker build -t adityah/github-action1:v1 -f Dockerfile .
    
    - name: push to dockerhub
      run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_SECRET}} && docker push adityah/github-action1:v1
nama: Tindakan GitHub ke Dockerhub run-name: ${{ github.actor }} uji Tindakan GitHub untuk mengunggah gambar buruh pelabuhan 🚀 aktif: [tekan] pekerjaan: Bangun-dan-dorong-gambar: berjalan: ubuntu-terbaru Langkah: - menggunakan: tindakan/checkout@v3 - nama: bangun dan tandai gambar lari: | docker build -t adityah/github-action1:v1 -f Dockerfile . - nama: Dorong ke dockerhub jalankan: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_SECRET}} && docker push adityah/github-action1:v1
translated from: English
